{
 "swagger": "2.0",
 "info": {
  "version": "3.38-SNAPSHOT build:112 ",
  "title": "inSign",
  "contact": {
   "name": "inSign Support",
   "url": "https://confluence.is2.de/display/IKB/",
   "email": "insign-support@is2.de"
  }
 },
 "host": "sandbox.insign.is2.show",
 "basePath": "/",
 "tags": [
  {
   "name": "Administrative",
   "description": "APIs for system administrative tasks"
  },
  {
   "name": "All Public",
   "description": "All public stable APIs"
  },
  {
   "name": "Document retrival",
   "description": "APIs for retrieving documents from sessions"
  },
  {
   "name": "Housekeeping",
   "description": "APIs for housekeeping functions"
  },
  {
   "name": "Internal",
   "description": "Internal APIs. Internal APIs may change without notice"
  },
  {
   "name": "Most common",
   "description": "Most commonly used public APIs"
  },
  {
   "name": "Process handling",
   "description": "APIs used for process handling"
  },
  {
   "name": "Session creation",
   "description": "APIs for creating new session"
  },
  {
   "name": "Session status information",
   "description": "APIs for getting status information about sessions or users"
  },
  {
   "name": "User handling",
   "description": "APIs for handling users and sessions belonging to a single user"
  }
 ],
 "schemes": [
  "http",
  "https"
 ],
 "paths": {
  "/admin/cron/reschedule/{id}": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Reschedule a cron job",
    "description": "Since 3.38",
    "operationId": "cronRescheduleUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Reschedule a cron job",
    "description": "Since 3.38",
    "operationId": "cronRescheduleUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/reset/{id}": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "resetTriggerFromErrorState a cron job",
    "description": "Since 3.38",
    "operationId": "cronResetTriggerFromErrorStateUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "resetTriggerFromErrorState a cron job",
    "description": "Since 3.38",
    "operationId": "cronResetTriggerFromErrorStateUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/resume/{id}": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Resume a cron job",
    "description": "Since 3.38",
    "operationId": "cronResumeUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Resume a cron job",
    "description": "Since 3.38",
    "operationId": "cronResumeUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/resumeall": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Resume the scheduler",
    "description": "Since 3.38",
    "operationId": "cronResumeAllUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Resume the scheduler",
    "description": "Since 3.38",
    "operationId": "cronResumeAllUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/runnow/{id}": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Resume a cron job",
    "description": "Since 3.38",
    "operationId": "cronRunNowUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Resume a cron job",
    "description": "Since 3.38",
    "operationId": "cronRunNowUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/status": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Get the status of the cron jobs",
    "description": "Since 3.38",
    "operationId": "cronStatusUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Get the status of the cron jobs",
    "description": "Since 3.38",
    "operationId": "cronStatusUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/suspend/{id}": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Pause a cron job",
    "description": "Since 3.38",
    "operationId": "cronPauseUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Pause a cron job",
    "description": "Since 3.38",
    "operationId": "cronPauseUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/cron/suspendall": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Pause the scheduler",
    "description": "Since 3.38",
    "operationId": "cronPauseAllUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative"
    ],
    "summary": "Pause the scheduler",
    "description": "Since 3.38",
    "operationId": "cronPauseAllUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/reloadProperties": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Force reload of properties. Usually not needed, but might be useful for docker.",
    "description": "Use with orderlist containing new ordering like: mydoc2,mydoc1,mydoc3,... all documents have to be listed",
    "operationId": "reloadPropertiesUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public"
    ],
    "summary": "Force reload of properties. Usually not needed, but might be useful for docker.",
    "description": "Use with orderlist containing new ordering like: mydoc2,mydoc1,mydoc3,... all documents have to be listed",
    "operationId": "reloadPropertiesUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/admin/systemcheckauto": {
   "get": {
    "tags": [
     "Administrative",
     "All Public"
    ],
    "summary": "System health check",
    "operationId": "systemCheckAutoUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN",
       "ROLE_INSIGN_SYSCHECK"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Administrative",
     "All Public"
    ],
    "summary": "System health check",
    "operationId": "systemCheckAutoUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN",
       "ROLE_INSIGN_SYSCHECK"
      ]
     }
    ]
   }
  },
  "/applos/qrcode": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Return the qrcode for a pairing code as image",
    "operationId": "getQRCodeUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Return the qrcode for a pairing code as image",
    "operationId": "getQRCodeUsingPOST"
   }
  },
  "/applos/resendApplosPermanentLink": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Resend applos permanent link",
    "operationId": "resendApplosPermanentLinkUsingPOST"
   }
  },
  "/applos/send": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Send out link for app-less signature",
    "operationId": "sendApplosLinkUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/aushaendigung/bestaetigen": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Confirm receipt of documents",
    "operationId": "bestaetigenUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Confirm receipt of documents",
    "operationId": "bestaetigenUsingPOST"
   }
  },
  "/aushaendigung/direct": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Direct link to download documents",
    "operationId": "aushaendigungDirectUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Direct link to download documents",
    "operationId": "aushaendigungDirectUsingPOST"
   }
  },
  "/aushaendigung/directExtern": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Direct link to download documents",
    "operationId": "aushaendigungDirectUsingGET_1"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Direct link to download documents",
    "operationId": "aushaendigungDirectUsingPOST_1"
   }
  },
  "/aushaendigung/getBestaetigungsdatum": {
   "get": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Retrieve document receipt confirmation timestamp",
    "operationId": "getBestaetigungsdatumUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Retrieve document receipt confirmation timestamp",
    "operationId": "getBestaetigungsdatumUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/aushaendigung/getPassword": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Get Password for Dokument",
    "operationId": "aushaendigungGetPasswordUsingGET",
    "deprecated": true
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Get Password for Dokument",
    "operationId": "aushaendigungGetPasswordUsingPOST",
    "deprecated": true
   }
  },
  "/auswertung/getjson": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Get the accounting data for one or all tenants",
    "operationId": "getAuswertungJSONUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_AUSWERTUNG",
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/ablehnen": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Abort and delete session",
    "operationId": "sessionloeschenUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Abort and delete session",
    "operationId": "sessionloeschenUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/activateWifiDirect": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Activate Wifi-Direct connection",
    "operationId": "activateWifiDirectUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Activate Wifi-Direct connection",
    "operationId": "activateWifiDirectUsingPOST"
   }
  },
  "/configure/addAdditionalDocument": {
   "post": {
    "tags": [
     "All Public"
    ],
    "summary": "Add one more documents metadata to a session after session creation.",
    "description": "The document binary might be upload separately later on or attached directly to this call",
    "operationId": "addAdditionalDocumentUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/adduser": {
   "post": {
    "tags": [
     "All Public",
     "User handling"
    ],
    "summary": "Create new user",
    "description": "Usually no need to call this as internal users are automatically created on session creation",
    "operationId": "adduserUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/beenden": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Finish session and return to callback url",
    "operationId": "sessionbeendenUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Finish session and return to callback url",
    "operationId": "sessionbeendenUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/changeOwner": {
   "post": {
    "tags": [
     "All Public",
     "User handling"
    ],
    "summary": "Change a sessions owner",
    "operationId": "changeSessionOwnerUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/cleanupdb": {
   "get": {
    "tags": [
     "All Public",
     "Housekeeping"
    ],
    "summary": "Cleanup database",
    "description": "Delete all session that have previously been marked as deleted from the database now. Usually no need to call this as it is usually trigger by an internal nightly cron job.",
    "operationId": "cleanUpDBUsingGET_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Housekeeping"
    ],
    "summary": "Cleanup database",
    "description": "Delete all session that have previously been marked as deleted from the database now. Usually no need to call this as it is usually trigger by an internal nightly cron job.",
    "operationId": "cleanUpDBUsingPOST_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Housekeeping"
    ],
    "summary": "Cleanup database",
    "description": "Delete all session that have previously been marked as deleted from the database now. Usually no need to call this as it is usually trigger by an internal nightly cron job.",
    "operationId": "cleanUpDBUsingDELETE_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/closesession": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Abort session and return to callback url",
    "operationId": "closesessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Abort session and return to callback url",
    "operationId": "closesessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/createSSO": {
   "post": {
    "tags": [
     "Internal",
     "User handling"
    ],
    "summary": "Create OTP token for internal start module",
    "operationId": "createTokenRequestUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/createSSOForApiuser": {
   "post": {
    "tags": [
     "Internal",
     "User handling"
    ],
    "summary": "Create JWT Token for API-User so that he can access internal start module",
    "operationId": "createTokenRequestApiUserUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/createconfigtemplate": {
   "post": {
    "tags": [
     "Session creation"
    ],
    "summary": "Add additional session configuration per mandant. If a configuration already exists, it will be updated.",
    "operationId": "createconfigtemplateUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/deletePage": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Remove a page from a document",
    "operationId": "deletePageUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Remove a page from a document",
    "operationId": "deletePageUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/deletedocument": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "User handling"
    ],
    "summary": "Remove a document from a session",
    "description": "Document is removed if possible (i.e. document is marked as deleteable).",
    "operationId": "deletedocumentUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "User handling"
    ],
    "summary": "Remove a document from a session",
    "description": "Document is removed if possible (i.e. document is marked as deleteable).",
    "operationId": "deletedocumentUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Most common",
     "User handling"
    ],
    "summary": "Remove a document from a session",
    "description": "Document is removed if possible (i.e. document is marked as deleteable).",
    "operationId": "deletedocumentUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/deletesession": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "No Operation",
    "operationId": "deletesessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ],
    "deprecated": true
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "No Operation",
    "operationId": "deletesessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ],
    "deprecated": true
   }
  },
  "/configure/deleteuser": {
   "get": {
    "tags": [
     "All Public",
     "Housekeeping",
     "Most common",
     "User handling"
    ],
    "summary": "Remove a user",
    "description": "Remove a user and all sessions belonging to this user (foruser/owner) from the database now.",
    "operationId": "deleteUserAndSessionsUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Housekeeping",
     "Most common",
     "User handling"
    ],
    "summary": "Remove a user",
    "description": "Remove a user and all sessions belonging to this user (foruser/owner) from the database now.",
    "operationId": "deleteUserAndSessionsUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Housekeeping",
     "Most common",
     "User handling"
    ],
    "summary": "Remove a user",
    "description": "Remove a user and all sessions belonging to this user (foruser/owner) from the database now.",
    "operationId": "deleteUserAndSessionsUsingDELETE",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/failureredirect": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Callback redirect on failure",
    "operationId": "redirectonfailureUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Callback redirect on failure",
    "operationId": "redirectonfailureUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/fertig": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Abort session and return to callback url",
    "operationId": "sessionabbrechenUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Abort session and return to callback url",
    "operationId": "sessionabbrechenUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/fertigVorgangsverwaltung": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Abort session and redirect to process manager",
    "operationId": "redirectToVorgangsverwaltungUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Abort session and redirect to process manager",
    "operationId": "redirectToVorgangsverwaltungUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/get/version": {
   "get": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get inSign version",
    "description": "Retrieve application version.",
    "operationId": "getVersionUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get inSign version",
    "description": "Retrieve application version.",
    "operationId": "getVersionUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/getproperties": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Get a list of possible UI-properties",
    "operationId": "getpropertiesUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Get a list of possible UI-properties",
    "operationId": "getpropertiesUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/initialCheck": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Session sanity check",
    "operationId": "initialCheckUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Session sanity check",
    "operationId": "initialCheckUsingPOST"
   }
  },
  "/configure/reorderDocuments": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Reorder documents after session creation.",
    "description": "Use with orderlist containing new ordering like: mydoc2,mydoc1,mydoc3,... all documents have to be listed",
    "operationId": "reorderDocumentsUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public"
    ],
    "summary": "Reorder documents after session creation.",
    "description": "Use with orderlist containing new ordering like: mydoc2,mydoc1,mydoc3,... all documents have to be listed",
    "operationId": "reorderDocumentsUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/resetsignatures": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Reset sessions signatures",
    "operationId": "resetSignaturesUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Reset sessions signatures",
    "operationId": "resetSignaturesUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/restartsession": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Reset sessions information",
    "description": "Reset documents to inital state after upload. Clear all signatures and input fields. Generate new TAN number.",
    "operationId": "restartsessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Reset sessions information",
    "description": "Reset documents to inital state after upload. Clear all signatures and input fields. Generate new TAN number.",
    "operationId": "restartsessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/session": {
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session creation"
    ],
    "summary": "Creates a new session with the provided metadata for the documents",
    "operationId": "configuredocumentsUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/sessionVorgangsverwaltung": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Session creation"
    ],
    "summary": "Creates a new session for process management",
    "operationId": "createVorgangsverwaltungSessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session creation"
    ],
    "summary": "Creates a new session for process management",
    "operationId": "createVorgangsverwaltungSessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/setSessionVar": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Set Session Var",
    "operationId": "setSessionVarUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/setcallbackurl": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Modify sessions callbackURL",
    "description": "If you want to modify the callbackURL property of an existing session",
    "operationId": "setcallbackurlUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Modify sessions callbackURL",
    "description": "If you want to modify the callbackURL property of an existing session",
    "operationId": "setcallbackurlUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/terminateWifiDirect": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "terminate Wifi-Direct connection",
    "operationId": "terminateWifiDirectUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "terminate Wifi-Direct connection",
    "operationId": "terminateWifiDirectUsingPOST"
   }
  },
  "/configure/updateGUIProperties": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Modify a list of session UI properties",
    "operationId": "setSessionGUIPropertyUsingPOST_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/updateGUIProperty": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Modify a session UI property",
    "operationId": "setSessionGUIPropertyUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Modify a session UI property",
    "operationId": "setSessionGUIPropertyUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/configure/updateSessionConfigProperty": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Modify a session mutable property",
    "operationId": "setSessionPropertyUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Modify a session mutable property",
    "operationId": "setSessionPropertyUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/uploaddocument": {
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session creation"
    ],
    "summary": "Upload a document into a previously configured session",
    "operationId": "uploaddocumentstreamUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/uploaddocumentie": {
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session creation"
    ],
    "summary": "Upload a document into a previously configured session",
    "operationId": "uploaddocumentstreammultipartieUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/uploadsummary": {
   "post": {
    "tags": [
     "All Public",
     "Session creation"
    ],
    "summary": "Add summary page to a previously configured session",
    "operationId": "uploadsummaryUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/configure/wifiDirectInfo": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Wifi-Direct connection status",
    "operationId": "getWifiDirectInfoUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Wifi-Direct connection status",
    "operationId": "getWifiDirectInfoUsingPOST"
   }
  },
  "/download/sendPassword": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Get Password for Dokument",
    "operationId": "sendPasswordFromEmailUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Get Password for Dokument",
    "operationId": "sendPasswordFromEmailUsingPOST"
   }
  },
  "/dualscreen/event": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Send event to client",
    "operationId": "pusheventUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Send event to client",
    "operationId": "pusheventUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/dualscreen/info": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "head": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingHEAD",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingPUT",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingDELETE",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "options": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingOPTIONS",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Internal"
    ],
    "summary": "Get information about clients",
    "operationId": "infoUsingPATCH",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER",
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/dualscreen/log": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingGET_2"
   },
   "head": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingHEAD_2"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingPOST_2"
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingPUT_2"
   },
   "delete": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingDELETE_2"
   },
   "options": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingOPTIONS_2"
   },
   "patch": {
    "tags": [
     "Internal"
    ],
    "summary": "Push client log to server",
    "operationId": "registerUsingPATCH_2"
   }
  },
  "/dualscreen/pull": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingGET_1"
   },
   "head": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingHEAD_1"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingPOST_1"
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingPUT_1"
   },
   "delete": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingDELETE_1"
   },
   "options": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingOPTIONS_1"
   },
   "patch": {
    "tags": [
     "Internal"
    ],
    "summary": "Poll for new dualscreen client information",
    "operationId": "registerUsingPATCH_1"
   }
  },
  "/dualscreen/pushcustomurl": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "head": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingHEAD",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingPUT",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingDELETE",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "options": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingOPTIONS",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Internal"
    ],
    "summary": "Send custom URL to client an wake him up",
    "operationId": "pushURLUsingPATCH",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER",
       "ROLE_RUN_AS_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/dualscreen/start": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Start Dualscreenmodus for session",
    "operationId": "startUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Start Dualscreenmodus for session",
    "operationId": "startUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/evaluation/getjson": {
   "get": {
    "tags": [
     "Administrative"
    ],
    "summary": "Get the accounting data for one or all tenants",
    "operationId": "getAuswertungJSONUsingGET_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_AUSWERTUNG",
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/exportSession": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Export a session as binary data.",
    "operationId": "exportSessionUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Export a session as binary data.",
    "operationId": "exportSessionUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/extern/abort": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Return session from external state",
    "operationId": "abortUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Return session from external state",
    "operationId": "abortUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/begin": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Start extern mode. Uses /beginmulti instead.",
    "operationId": "setExternalUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ],
    "deprecated": true
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Start extern mode. Uses /beginmulti instead.",
    "operationId": "setExternalUsingPUT_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ],
    "deprecated": true
   }
  },
  "/extern/beginmulti": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Start extern mode and creates users for this mode. Do not set skipLandingPage=true if you plan to send links by mail.",
    "operationId": "setExternalUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Start extern mode and creates users for this mode. Do not set skipLandingPage=true if you plan to send links by mail.",
    "operationId": "setExternalUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/delegate": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Redirect extern process to another user",
    "operationId": "delegateUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Redirect extern process to another user",
    "operationId": "delegateUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/delegate/finished": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Confirm receipt of documents",
    "operationId": "dummyUsingGET_1"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Confirm receipt of documents",
    "operationId": "dummyUsingPOST_1"
   }
  },
  "/extern/newtoken": {
   "get": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Reaktivate external user token and create new password for user if token was renewed",
    "operationId": "newTokenUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Reaktivate external user token and create new password for user if token was renewed",
    "operationId": "newTokenUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Reaktivate external user token and create new password for user if token was renewed",
    "operationId": "newTokenUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/resetlastSignature": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Redirect extern process to another user",
    "operationId": "resetSignatureUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Redirect extern process to another user",
    "operationId": "resetSignatureUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/setExternExpirationDate": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Set expiration Date to return session automatically from external state",
    "operationId": "setExternExpirationDateUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Set expiration Date to return session automatically from external state",
    "operationId": "setExternExpirationDateUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/status": {
   "get": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Retrieve status about external user",
    "operationId": "getStatusUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/updateUser": {
   "post": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Update external user information",
    "operationId": "updateExternUserUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Update external user information",
    "operationId": "updateExternUserUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/extern/updatetoken": {
   "post": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Reaktivate external user token and create new password for user",
    "operationId": "updateTokenUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Process handling",
     "User handling"
    ],
    "summary": "Reaktivate external user token and create new password for user",
    "operationId": "updateTokenUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/audit/download": {
   "get": {
    "tags": [
     "Document retrival"
    ],
    "summary": "Download the audit report for a process",
    "operationId": "downloadDocumentsUsingGET_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Document retrival"
    ],
    "summary": "Download the audit report for a process",
    "operationId": "downloadDocumentsUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/blobdata": {
   "get": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get session custom blob data",
    "operationId": "getBlobDataUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get session custom blob data",
    "operationId": "getBlobDataUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/get/cachedsessionids": {
   "get": {
    "tags": [
     "Internal",
     "Session status information"
    ],
    "summary": "List of session currently in cache",
    "operationId": "getSessionsUsingGET_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal",
     "Session status information"
    ],
    "summary": "List of session currently in cache",
    "operationId": "getSessionsUsingPOST_1",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/get/checkstatus": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Session status information"
    ],
    "summary": "Get session status information",
    "operationId": "getCheckStatusUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_ALLOWNULLSESSION",
       "CONTENT_CHECKSTATUS"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session status information"
    ],
    "summary": "Get session status information",
    "operationId": "getCheckStatusUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_ALLOWNULLSESSION",
       "CONTENT_CHECKSTATUS"
      ]
     }
    ]
   }
  },
  "/get/document": {
   "get": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Download single document containing the current signatures and modifications",
    "operationId": "getDocumentUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Download single document containing the current signatures and modifications",
    "operationId": "getDocumentUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/documents/by/ids": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve metadata about one sessions document and annotations",
    "operationId": "getFullDocumentDataByIdsUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve metadata about one sessions document and annotations",
    "operationId": "getFullDocumentDataByIdsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/documents/download": {
   "get": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Download all sessions documents as single zip file",
    "operationId": "downloadDocumentsUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Download all sessions documents as single zip file",
    "operationId": "downloadDocumentsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/documents/downloadmulti": {
   "get": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Download several session documents as zips in zip file",
    "operationId": "downloadDocumentsMultiUsingGET_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_ALLOWNULLSESSION"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Download several session documents as zips in zip file",
    "operationId": "downloadDocumentsMultiUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_ALLOWNULLSESSION"
      ]
     }
    ]
   }
  },
  "/get/documents/enveloped": {
   "get": {
    "tags": [
     "All Public",
     "Document retrival"
    ],
    "summary": "Attach sessions current documents to the provided container pdf-file",
    "operationId": "getEnvelopedDocumentsUsingGET_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Document retrival"
    ],
    "summary": "Attach sessions current documents to the provided container pdf-file",
    "operationId": "getEnvelopedDocumentsUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "All Public",
     "Document retrival"
    ],
    "summary": "Attach sessions current documents to the provided container pdf-file",
    "operationId": "getEnvelopedDocumentsUsingPUT_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/documents/full": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve metadata about all sessions documents and annotations",
    "operationId": "getFullDocumentDataUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve metadata about all sessions documents and annotations",
    "operationId": "getFullDocumentDataUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/documents/gwg": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Retrieve information about ID-Card photos from a session",
    "operationId": "getGWGInfosUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public"
    ],
    "summary": "Retrieve information about ID-Card photos from a session",
    "operationId": "getGWGInfosUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/externInfos": {
   "get": {
    "tags": [
     "Internal",
     "Process handling",
     "Session status information"
    ],
    "summary": "Additional status information about session that is in external state",
    "operationId": "getExternInfosUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_DENIE_CUSTOMER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal",
     "Process handling",
     "Session status information"
    ],
    "summary": "Additional status information about session that is in external state",
    "operationId": "getExternInfosUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_DENIE_CUSTOMER"
      ]
     }
    ]
   }
  },
  "/get/querysessions": {
   "post": {
    "tags": [
     "All Public",
     "Process handling",
     "Session status information"
    ],
    "summary": "Retrieve information about a bunch of sessions",
    "operationId": "getSessionsUsingPOST_3",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/get/resetAusgehaendigt": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Set ausgehaendigtOriginal to false",
    "operationId": "resetAusgehaendigtOriginalUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Set ausgehaendigtOriginal to false",
    "operationId": "resetAusgehaendigtOriginalUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Set ausgehaendigtOriginal to false",
    "operationId": "resetAusgehaendigtOriginalUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/sessionowner": {
   "get": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Get owner of a session",
    "operationId": "getUserForSessionsUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Get owner of a session",
    "operationId": "getUserForSessionsUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/get/sessions": {
   "get": {
    "tags": [
     "Internal",
     "Session status information"
    ],
    "summary": "List of session",
    "operationId": "getSessionsUsingGET_2",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_DENIE_CUSTOMER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal",
     "Session status information"
    ],
    "summary": "List of session",
    "operationId": "getSessionsUsingPOST_2",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_DENIE_CUSTOMER"
      ]
     }
    ]
   }
  },
  "/get/setDisplay": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Set displayname and customer name of a session",
    "operationId": "setDisplayUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Set displayname and customer name of a session",
    "operationId": "setDisplayUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/setDocDisplay": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Set the displayname of a document",
    "operationId": "setDocDisplayUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Internal"
    ],
    "summary": "Set the displayname of a document",
    "operationId": "setDocDisplayUsingPUT",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/signature/signed": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Checks if given signature is already signed.",
    "operationId": "isSignatureSignedUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/status": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Session status information"
    ],
    "summary": "Get session status information",
    "operationId": "getStatusUsingGET_2",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session status information"
    ],
    "summary": "Get session status information",
    "operationId": "getStatusUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/statuswithload": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Session status information"
    ],
    "summary": "Get session status information and load session into memory if not already loaded",
    "operationId": "getStatusLoadableUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Session status information"
    ],
    "summary": "Get session status information and load session into memory if not already loaded",
    "operationId": "getStatusLoadableUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/get/usersessions": {
   "get": {
    "tags": [
     "All Public",
     "Process handling",
     "Session status information"
    ],
    "summary": "List of session that belong to a single user. You can also pass a user list separated by 'separator' for multiple users",
    "operationId": "getSessionsUsingGET_4",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling",
     "Session status information"
    ],
    "summary": "List of session that belong to a single user. You can also pass a user list separated by 'separator' for multiple users",
    "operationId": "getSessionsUsingPOST_4",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/get/vorgangsnummer": {
   "get": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get session Transaction number (TAN)",
    "operationId": "getTransaktionsnummerUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get session Transaction number (TAN)",
    "operationId": "getTransaktionsnummerUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/getSessionInfoForExport": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Get session metadata for export",
    "operationId": "getSessionInfoUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Get session metadata for export",
    "operationId": "getSessionInfoUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/getimage/signature": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Get a signatures bitmap as PNG image.",
    "operationId": "getSignatureImageUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/image/getdocumentpageimage": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Render a documents page as PNG Bitmap",
    "operationId": "getDocumentPageImageUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/image/getdocumentpageimageb64": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Render a documents page as PNG Bitmap. Returns Base64 data.",
    "operationId": "getDocumentPageImageB64UsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/image/getdocumentthumbnail": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Render a documents page as PNG Thumbnail-Bitmap",
    "operationId": "getDocumentThumbnailUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/image/getdocumentthumbnail64": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Render a documents page as PNG Thumbnail-Bitmap. Returns Base64 data.",
    "operationId": "getDocumentThumbnailB64UsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/importSession": {
   "get": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Import binary session data",
    "operationId": "importSessionUsingGET",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Import binary session data",
    "operationId": "importSessionUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/mail/documents/download": {
   "get": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Retrieve all sessions documents as single zip file. Might return PDF for single document",
    "operationId": "downloadDocumentsProtectedUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_DOWNLOADER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Retrieve all sessions documents as single zip file. Might return PDF for single document",
    "operationId": "downloadDocumentsProtectedUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_DOWNLOADER"
      ]
     }
    ]
   }
  },
  "/mail/get/data": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve information about E-Mails and subject for client UI",
    "operationId": "getMailDataUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/mail/preview": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Render Mail template for client UI",
    "operationId": "getMailDataUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/mail/send": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Send out E-Mails",
    "operationId": "sendAllDocumentsApiUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/delete": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Mark session as deleted",
    "operationId": "deleteSessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Mark session as deleted",
    "operationId": "deleteSessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Mark session as deleted",
    "operationId": "deleteSessionUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/deleteall": {
   "get": {
    "tags": [
     "Housekeeping",
     "User handling"
    ],
    "summary": "Mark all sessions of the sessions owner as deleted",
    "operationId": "deleteAllSessionsUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Housekeeping",
     "User handling"
    ],
    "summary": "Mark all sessions of the sessions owner as deleted",
    "operationId": "deleteAllSessionsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Housekeeping",
     "User handling"
    ],
    "summary": "Mark all sessions of the sessions owner as deleted",
    "operationId": "deleteAllSessionsUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/deletedocument": {
   "get": {
    "tags": [
     "All Public"
    ],
    "summary": "Remove document from session. Remove session if no documents left in the session after the operation.",
    "operationId": "deleteDocumentUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public"
    ],
    "summary": "Remove document from session. Remove session if no documents left in the session after the operation.",
    "operationId": "deleteDocumentUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public"
    ],
    "summary": "Remove document from session. Remove session if no documents left in the session after the operation.",
    "operationId": "deleteDocumentUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/deletemarked": {
   "get": {
    "tags": [
     "Housekeeping",
     "User handling"
    ],
    "summary": "Delete all session marked as deleted of the sessions owner permanently",
    "operationId": "deleteMarkedSessionsUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Housekeeping",
     "User handling"
    ],
    "summary": "Delete all session marked as deleted of the sessions owner permanently",
    "operationId": "deleteMarkedSessionsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Housekeeping",
     "User handling"
    ],
    "summary": "Delete all session marked as deleted of the sessions owner permanently",
    "operationId": "deleteMarkedSessionsUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/loadsession": {
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Load session from database",
    "operationId": "loadSessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_LOCK_IN_USE"
      ]
     }
    ]
   }
  },
  "/persistence/purge": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Remove session by TAN oder sessionid. Removes session from memory.",
    "operationId": "purgeSessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Remove session by TAN oder sessionid. Removes session from memory.",
    "operationId": "purgeSessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Remove session by TAN oder sessionid. Removes session from memory.",
    "operationId": "purgeSessionUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/recoverdeleted": {
   "get": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Unmark all sessions of an user which are marked as deleted",
    "operationId": "recoverdeleteSessionsUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Unmark all sessions of an user which are marked as deleted",
    "operationId": "recoverdeleteSessionsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Document retrival",
     "Most common"
    ],
    "summary": "Unmark all sessions of an user which are marked as deleted",
    "operationId": "recoverdeleteSessionsUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/persistence/unloadsession": {
   "get": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Unload session from memory",
    "operationId": "unloadSessionUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Unload session from memory",
    "operationId": "unloadSessionUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public",
     "Most common",
     "Process handling"
    ],
    "summary": "Unload session from memory",
    "operationId": "unloadSessionUsingDELETE",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/qes/get/tans": {
   "get": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Get external providers tans of all completed QES / Video-Idents for session",
    "operationId": "getQESTansUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "All Public",
     "Session status information"
    ],
    "summary": "Get external providers tans of all completed QES / Video-Idents for session",
    "operationId": "getQESTansUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/qes/yes/cert": {
   "post": {
    "tags": [
     "All Public"
    ],
    "summary": "CRUD operation for yes certificates",
    "operationId": "updateCertUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "All Public"
    ],
    "summary": "CRUD operation for yes certificates",
    "operationId": "deleteCertUsingDELETE",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_ADMIN"
      ]
     }
    ]
   }
  },
  "/reconfigureSession": {
   "post": {
    "tags": [
     "All Public",
     "Process handling"
    ],
    "summary": "Reconfigure a session",
    "operationId": "reconfigureSessionUsingPOST",
    "security": [
     {
      "basic": [
       "ROLE_INSIGN_CONTROLLER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/checktoken": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Check existing pairing token",
    "operationId": "checkTokenUsingPOST"
   }
  },
  "/rest/mobilepairing/getPairingCodeInfo": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Request info about pairing code",
    "operationId": "getPairingCodeInfoUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/getpaireddevice": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve information about paired signature devices",
    "operationId": "getPairedDeviceUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/getpairedmobiles": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve infomation about paired signature devices",
    "operationId": "getpairedmobilesUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_ALLOWNULLSESSION"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve infomation about paired signature devices",
    "operationId": "getpairedmobilesUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER",
       "CONTENT_ALLOWNULLSESSION"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/needspairing": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Retrieve information about pairing needed",
    "operationId": "needsPairingUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/pairmobile": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Pair device",
    "operationId": "pairMobileUsingPOST"
   }
  },
  "/rest/mobilepairing/requestcode": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Request new pairing code",
    "operationId": "requestPairingCodeUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/setWifiID": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Set Wifi-Direct-ID for pairingcode",
    "operationId": "setWifiDirectIDUsingPOST"
   }
  },
  "/rest/mobilepairing/unpair": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair signature device",
    "operationId": "unpairUsingPOST_1"
   }
  },
  "/rest/mobilepairing/unpairall": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all paired users signature devices",
    "operationId": "unpairUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all paired users signature devices",
    "operationId": "unpairUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/unpairallCustomer": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all additional (customer) devices",
    "operationId": "unpairCustomerUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all additional (customer) devices",
    "operationId": "unpairCustomerUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/unpairallUser": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all additional user devices",
    "operationId": "unpairUserUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all additional user devices",
    "operationId": "unpairUserUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/unpairallforuser": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all paired users signature devices",
    "operationId": "unpairallforuserUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Unpair all paired users signature devices",
    "operationId": "unpairallforuserUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/mobilepairing/whoispairingmobile": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Determine type of pairing code",
    "operationId": "whoIsPairingMobileUsingPOST"
   }
  },
  "/rest/signprocess/cancel": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Cancel the sign process.",
    "operationId": "cancelSignProcessUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/signprocess/cancelfoto": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Cancel the foto process.",
    "operationId": "cancelFotoProcessUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/signprocess/getDataForSign": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Get data for signature.",
    "operationId": "getHashForDocumentUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/signprocess/getSignappData": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Get data for sign app.",
    "operationId": "getSignappDataUsingPOST"
   }
  },
  "/rest/signprocess/initialApplosRegister": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Initial registration for app-less signing.",
    "operationId": "registerApplosClientTokenAuthUsingPOST"
   }
  },
  "/rest/signprocess/registerclient": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Register a client.",
    "operationId": "registerSignpadClientTokenAuthUsingPOST"
   }
  },
  "/rest/signprocess/sendnotify": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Send a notification to participants.",
    "operationId": "sendNotificationUsingPOST"
   }
  },
  "/rest/signprocess/start": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Start the sign process.",
    "operationId": "startSignProcessUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/signprocess/startfoto": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Start the foto process.",
    "operationId": "startFotoProcessUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/signprocess/waitfornotify": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Wait for a notification.",
    "operationId": "waitForNotificationUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/store/documents": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Store documents data (signatures, form fields)",
    "operationId": "storeMultipleDocumentsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/store/photo": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Upload photo",
    "operationId": "uploadphotostream2UsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/store/photoApplos": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Upload photo",
    "operationId": "uploadphotoApplosUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/store/private": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Modify the access to a session ",
    "operationId": "storePrivateUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/rest/store/signature": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Store single signature",
    "operationId": "storeSignatureUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/s/{id}": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Shortened link expansion via redirect to full url",
    "operationId": "expandlinkUsingGET"
   },
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Shortened link expansion via redirect to full url",
    "operationId": "expandlinkUsingPOST"
   }
  },
  "/serialProcess/begin": {
   "post": {
    "tags": [
     "All Public",
     "Session creation"
    ],
    "summary": "Creates a separate process for each signatory and sends it out for signature request",
    "description": "The limit is 'serial.process.maxlimit'<br/>Not applicable for 'extern.per.sms'",
    "operationId": "beginUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/serialProcess/data": {
   "get": {
    "tags": [
     "Internal"
    ],
    "summary": "Additional data required for the dialog",
    "operationId": "getDataUsingGET",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/serialProcess/getResults": {
   "post": {
    "tags": [
     "All Public",
     "Session creation"
    ],
    "summary": "List of the state of the execution of an serial process begin call",
    "description": "Pending results are not executed yet",
    "operationId": "getResultsUsingPOST",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  },
  "/version": {
   "get": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get inSign version",
    "description": "Retrieve application version.",
    "operationId": "getVersionUsingGET_1"
   },
   "post": {
    "tags": [
     "All Public",
     "Most common"
    ],
    "summary": "Get inSign version",
    "description": "Retrieve application version.",
    "operationId": "getVersionUsingPOST_1"
   }
  },
  "/waitForNotification": {
   "post": {
    "tags": [
     "Internal"
    ],
    "summary": "Multi device messaging. Long term polling",
    "operationId": "waitForNotificationUsingPOST_1",
    "security": [
     {
      "basic": [
       "CONTENT_OWNER"
      ]
     }
    ]
   }
  }
 },
 "securityDefinitions": {
  "basic": {
   "type": "basic"
  }
 }
}